// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetLatestSpreads():Promise<Array<models.SpreadSignal>>;

export function UpdateConfig(arg1:models.EngineConfig):Promise<void>;

export function UpdateSpreadConfig(arg1:models.SpreadConfig):Promise<void>;
