// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestSpreads() {
  return window['go']['app']['App']['GetLatestSpreads']();
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}

export function UpdateSpreadConfig(arg1) {
  return window['go']['app']['App']['UpdateSpreadConfig'](arg1);
}
